const {chromium}=require(process.env.PLAYWRIGHT_CORE || '/workspace/scratch/browser-tools/node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs'),{execFileSync}=require('node:child_process');
(async()=>{const cdp=execFileSync('/workspace/scratch/browser-tools/node_modules/.bin/agent-browser',['get','cdp-url'],{encoding:'utf8'}).trim();const browser=await chromium.connectOverCDP(cdp);const context=browser.contexts()[0],page=await context.newPage();let checks=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));const origin=process.argv[2]||'http://localhost:4181';
await page.goto(origin);await page.locator('#result-mode').filter({hasText:'Precomputed example'}).waitFor();assert.equal(await page.locator('#score').innerText(),'76.0');checks++;
const manifest=JSON.parse(fs.readFileSync('/workspace/speechtrace/public/data/dataset.json'));
for(const c of manifest.cases){await page.locator('#example').selectOption(c.id);await page.locator('#load-example').click();await page.waitForFunction(label=>document.querySelector('#result-context').textContent.includes(label)&&!document.querySelector('#results').hidden,c.label);assert.equal(Number(await page.locator('#score').innerText()),c.result.score);assert.equal(await page.locator('#regions article').count(),c.result.regions.length);checks++;}
await page.locator('#example').selectOption('power-moderate-volume');await page.locator('#load-example').click();await page.waitForFunction(()=>document.querySelector('#score').textContent==='76.0');await page.locator('#analyze').click();await page.locator('#result-mode').filter({hasText:'Fresh analysis'}).waitFor({timeout:80000});assert.equal(await page.locator('#score').innerText(),'76.0');assert.match(await page.locator('#alignment-summary').innerText(),/100%/);checks++;
await page.locator('#regions button').first().click();assert.ok(Number(await page.locator('#seek').inputValue())>=2.8);await page.locator('#words button').nth(4).click();assert.ok(Number(await page.locator('#seek').inputValue())>0);checks++;
const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]);const stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk;assert.equal(JSON.parse(text).score,76);checks++;
await page.locator('#clear').click();assert.equal(await page.locator('#results').isVisible(),false);assert.equal(await page.locator('#transcript').inputValue(),'');assert.equal(await page.locator('#participant-audio').getAttribute('src'),null);await page.locator('#analyze').click();assert.match(await page.locator('#error').innerText(),/both recordings/);checks++;
await page.locator('#upload-panel').evaluate(e=>e.open=true);
const base='/workspace/speechtrace/public/data/';const target=manifest.cases.find(c=>c.id==='power-moderate-volume');
// Intentionally overlap decoding: independent file uploads must both survive.
await Promise.all([page.locator('#baseline-file').setInputFiles(base+target.baseline.split('/').pop()),page.locator('#participant-file').setInputFiles(base+target.participant.split('/').pop())]);await page.waitForFunction(()=>!document.querySelector('#analyze').disabled);await page.locator('#transcript-file').setInputFiles(base+'power-transcript.txt');await page.waitForFunction(()=>document.querySelector('#transcript').value.length>40);await page.locator('#analyze').click();await page.locator('#result-mode').filter({hasText:'Fresh analysis'}).waitFor({timeout:80000});assert.equal(await page.locator('#score').innerText(),'76.0');checks++;
// Real input conversion of stereo 44.1kHz is exercised with an FFmpeg-produced test file.
execFileSync('ffmpeg',['-y','-loglevel','error','-i',base+target.participant.split('/').pop(),'-ar','44100','-ac','2','/tmp/speech-stereo.wav']);await page.locator('#participant-file').setInputFiles('/tmp/speech-stereo.wav');await page.waitForFunction(()=>!document.querySelector('#analyze').disabled);await page.locator('#analyze').click();await page.locator('#result-mode').filter({hasText:'Fresh analysis'}).waitFor({timeout:80000});assert.ok(Math.abs(Number(await page.locator('#score').innerText())-76)<2);checks++;
await page.locator('#participant-file').setInputFiles({name:'broken.wav',mimeType:'audio/wav',buffer:Buffer.from('invalid')});await page.waitForFunction(()=>!document.querySelector('#analyze').disabled);assert.match(await page.locator('#error').innerText(),/Could not prepare/);await page.locator('#analyze').click();assert.match(await page.locator('#error').innerText(),/both recordings/);checks++;
// Delay an actual API response and edit the transcript before it returns.
await page.locator('#load-example').click();await page.waitForFunction(()=>!document.querySelector('#results').hidden);await page.route('**/api/analyze',async route=>{const response=await route.fetch();await new Promise(r=>setTimeout(r,600));try{await route.fulfill({response});}catch(e){if(!/already handled/.test(e.message))throw e;}});await page.locator('#analyze').click();await page.locator('#transcript').fill('changed transcript');await page.waitForTimeout(1200);assert.equal(await page.locator('#results').isVisible(),false);assert.equal(await page.locator('#analyze').isEnabled(),true);await page.unroute('**/api/analyze');checks++;
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.locator('#load-example').click();await page.waitForFunction(()=>!document.querySelector('#results').hidden);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow at '+width);checks++;if(width===390)await page.screenshot({path:'/workspace/hackathon-submissions/SpeechTrace-mobile.png',fullPage:true});}
assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>[localStorage.length,sessionStorage.length]),[0,0]);checks+=2;
await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/workspace/hackathon-submissions/SpeechTrace-dashboard.png',fullPage:true});await page.locator('#example').selectOption('beliefs-extra-pause');await page.locator('#load-example').click();await page.waitForFunction(()=>document.querySelector('#result-context').textContent.includes('Extra pause'));await page.screenshot({path:'/workspace/hackathon-submissions/SpeechTrace-pause.png',fullPage:true});await page.goto(origin+'/docs.html');assert.ok(await page.locator('body').innerText().then(t=>t.includes('0.975')));const response=await page.request.get(origin+'/SpeechTrace-technical.pdf');assert.equal(response.status(),200);checks+=2;
await page.close();await browser.close();console.log(JSON.stringify({origin,checks,consoleErrors:errors,status:'passed'}));})().catch(e=>{console.error(e);process.exit(1)});
